services:
  nginx:
    container_name: kajimc_nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./kajimc:/var/www/html
      - ./logs/nginx:/var/log/nginx
    networks:
      - proxy-network
    restart: unless-stopped
    environment:
      NAME1: ${NAME1}
      NAME2: ${NAME2}
      NAME3: ${NAME3}
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    tmpfs:
      - /var/cache/nginx
      - /var/run

  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        TZ: ${TZ}
        PUID: ${PUID}
        PGID: ${PGID}
    expose:
        - "8443" # HTTPS
    ports:
        # - "8123:8123" # DYNMAP
        # - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ./crafty_container/backups:/crafty/backups
        - ./crafty_container/logs:/crafty/logs
        - ./crafty_container/servers:/crafty/servers
        - ./crafty_container/config:/crafty/app/config
        - ./crafty_container/import:/crafty/import
    networks:
        - proxy-network
    depends_on:
        - nginx

  kajiedi-frontend:
    container_name: kajiedi_frontend
    build:
      context: ./kajiedi/frontend
    expose:
      - "80"
    networks:
      - proxy-network
    depends_on:
      - nginx
    restart: unless-stopped

  kajiedi-backend:
    container_name: kajiedi_backend
    build:
      context: ./kajiedi/backend
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LUA_DIR}:/lua/computer
      - ./logs/kajiedi:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - proxy-network
    depends_on:
      - nginx
    restart: unless-stopped

  kajimc-php:
    container_name: kajimc_php
    image: php:8.4-fpm
    volumes:
      - ./kajimc:/var/www/html
      - ./logs/php:/var/log/php
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      ADMIN_IPS: ${ADMIN_IPS}
    user: "${PUID}:${PGID}"
    networks:
      - proxy-network
    restart: unless-stopped
    depends_on:
      - nginx

networks:
  proxy-network:
    driver: bridge
